<?php

namespace AppBundle\Repository;

/**
 * WebsiteParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteParamsRepository extends \Doctrine\ORM\EntityRepository
{
}
